# Matriks

Topik dibahas:
* definisi matriks
* membuat matriks dari list
* membuat matriks menggunakan perulangan
* operasi dasar pada matriks
* Penggunaan NumPy untuk matriks

# Matriks

Matriks adalah suatu bilangan atau simbol yang disusun dalam baris dan kolom. Isi dari matriks disebut sebagai elemen-elemen matriks. Penulisan elemen matriks tersebut berada dalam kurung ( ... ) atau [ ... ]. Elemen horizontal disebut sebagai baris ( biasa disimbolkan dengan m), kemudian elemen vertikal disebut sebagai kolom (biasa disimbolkan sebagai n).

Perhatikan ilustrasi sebuah matrik di bawah ini. Matriks A berisi sembilan elemen, dimana jumlah baris (m) adalah 3 dan jumlah kolom (n) adalah 3, atau dapat dinyatakan bahwa matrik A berukuran 3 x 3. Adapun bentuk umum matriks seperti disajikan pada gambar berikutnya.

<img src="images/w12matriks_contoh.JPG">

<img src="images/w12matriks_simbol.JPG">

## Membuat Matrik dari List

Pada bahasa pemrograman python, matriks digambarkan sebagai list bersarang atau _nested list_ atau list dua dimensi. Berikut ini ilustrasi membuat matriks. 

In [3]:
# matriks berukuran 2 x 2
matriksA = [ [1, 2], 
             [3, 4] ]

print(matriksA)

[[1, 2], [3, 4]]


In [4]:
# matriks berukuran 3 x 2
matriksB = [ [1, 2], 
             [3, 4], 
             [5, 6] ]

print(matriksB)

[[1, 2], [3, 4], [5, 6]]


In [15]:
# matriks berukuran 4 x 4
matriksC = [ [1, 2, 3, 4], 
             [5, 6, 7, 8], 
             [9, 10, 11, 12], 
             [13, 14, 15, 16] ]

print(matriksC)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
15


Perhatikan bahwa contoh di bawah ini  bukanlah matriks, melainkan hanyalah sebuah list dua dimensi atau nested list atau list bersarang saja. Hal ini karena jumlah elemen pada setiap baris atau kolom tidak sama.

In [6]:
# Bukan matriks
bukanMatriks = [ [1, 2, 3, 4], 
             [5, 6 ], 
             [9, 10, 11, 12], 
             [13, 14, 15, 16] ]

print(bukanMatriks)

[[1, 2, 3, 4], [5, 6], [9, 10, 11, 12], [13, 14, 15, 16]]


## Mengakses sebuah Elemen pada Matriks
Mengakses sebuah elemen pada matriks sebagaimana mengakses list menggunakan indeks-nya. Harus kembali diingat bahwa indeks list tersebut dimulai dari nol ( 0 ).


In [17]:
print(matriksA[1][1])
print(matriksC[2][0])
print(matriksC[3][2])

4
9
15


## Membuat Matriks menggunakan Perulangan

Membuat matriks dapat dilakukan menggunakan blok program perulangan menggunakan _for_. Perhatikan contoh di bawah ini.

In [11]:
m = 4
n = 3
MA  = [0] * m

for i in range(m):
    MA[i] = [1] * n

print(MA)

[[1, 1, 1], [1, 1, 1], [1, 1, 1], [1, 1, 1]]


Contoh di atas mengilustrasikan pembuatan matrik berukuran m x n atau dimana jumlah baris atau m adalah 4 dan jumlah kolom atau n adalah 3. 

Langkah berikutnya adalah mendeklarasikan variabel list atau matriks MA yang jumlah barisnya adalah m dengan menuliskan 
<i> 
    
    MA = [0] * m   # Hasil proses ini adalah [0, 0, 0, 0]
</i>

Kemudian buat perulangan sebanyak m ( 4 kali) dimulai dari indeks 0.
<i> 
    
    for i in range(m):  
</i>

Kemudian untuk setiap MA[i] diberikan nilai list satu dimensi berukuran _n_ yang isinya adalah bilangan 1.
<i> 
    
    MA[i] = [1] * n  
</i>



Cara lain untuk mengisi elemen matrik adalah menggunakan perulangan bersarang, atau nested for. Namun demikian, matriks tersebut sudah harus terdefinisi atau terbentuk terlebih dahulu dengan menggunakan proses yang dicoontohkan sebelumnya.

In [21]:
m = 4
n = 5
MB  = [0] * m
for i in range(m):
    MB[i] = [0] * n
    
for i in range(0, m):
    for j in range(0, n):
        MB[i][j] = i+j

print(MB)

[[0, 1, 2, 3, 4], [1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7]]


## Mengakses Elemen Matriks Menggunakan Perulangan

In [22]:
MatA = [
    [3, 2],
    [0, 6],
]
for x in range(0, len(MatA)):
    for y in range(0, len(MatA[0])):
        print (MatA[x][y], end=' '),
    print ()

3 2 
0 6 


In [23]:
for i in range(0, len(matriksC)):
    for j in range(0, len(matriksC[0])):
        print (matriksC[i][j], end=' '),
    print ()

1 2 3 4 
5 6 7 8 
9 10 11 12 
13 14 15 16 


## Operasi Dasar pada Matriks

Pada bagian ini ditunjukkan operasi dasar pada matriks yaitu penjumlahan, pengurangan dan perkalian.

### 1. Penjumlahan Matriks
Penjumlahan matriks dapat di lakukan pada matriks yang berukuran (ordo) sama. Setiap element pada matriks di jumlahkan satu persatu sehingga mendapat hasil yang di tata sesuai ordo awal.

In [26]:
MatA = [
    [8, 2],
    [4, 6],
]
MatB = [
    [3, 5],
    [1, 3],
]
for i in range(0, len(MatA)):
    for j in range(0, len(MatA[0])):
        print (MatA[i][j] + MatB[i][j], end=' '),
    print ()

11 7 
5 9 


### 2. Pengurangan Matriks

Pengurangan pada matriks sama seperti proses penjumlahan matriks, dengan mengganti operator (+) menjadi (-)

In [ ]:
for i in range(0, len(MatA)):
    for j in range(0, len(MatA[0])):
        print (MatA[i][j] i MatB[i][j], end=' '),
    print ()

#### Latihan Mandiri
Bagaimana jika hasil penjumlahan disimpan pada matriks dengan nama MatC ? dan hasil pengurangan matriks disimpan pada matriks dengan nama MatD ?

### 3 Perkalian Matriks

Perkalian matriks dilakukan dengan menjumlahkan hasil perkalian suatu baris matriks pertama ke kolom matriks kedua. Setiap baris di matriks pertama akan dikalikan ke setiap kolom di matriks kedua.

Proses perkalian matriks menggunakan nested loop for di dalam nested loop yang kedua. Perulangan ketiga digunakan untuk melakukan proses penjumlahan hasil perkalian baris dan kolom. Hasilnya elemen matriks baru akan ditempatkan pada koordinat tersebut.

<img src="images/w12matriks_perkalian.JPG">

<img src="images/w12MatrikEdanF.png">

In [10]:
matE = [
        [0.16426444, 0.86066735],
        [0.66929087, 0.3290199 ],
        [0.38433369, 0.6765218 ]
]

matF = [
    [0.43122339, 0.95886182, 0.412917  ],
    [0.03569391, 0.10067637, 0.8138365 ]
]

matG = []
# print(len(matE))
# print(len(matE[0]))
# print(len(matF))
# print(len(matF[0]))

for x in range(0, len(matE)):
    row = []
    for y in range(0, len(matE)):
        total = 0
        for z in range(0, len(matF)):
            total = total + (matE[x][z] * matF[z][y])
        row.append(total)
    matG.append(row)
    
for x in range(0, len(matG)):
    for y in range(0, len(matG[0])):
        print (matG[x][y], end=' ')
    print ()

0.1015552516040901 0.24415576447520032 0.768270083559755 
0.3003578845562583 0.6748819909073465 0.54412998201414 
0.1898813849352471 0.4366326605305818 0.70927604815943 


## NumPy untuk Operasi Matriks

NumPy adalah sebuah modul untuk Python --> "Numeric Python" or "Numerical Python". NumPy memperkaya bahasa pemrograman python melalui struktur data, implementasi multi-dimensional arrays dan matriks. NumPy memberikan kemudahan untuk mengolah data matriks skala besar dan berbagai proses operasi matriks lainnya. Keuntungan lain penggunaan NumPy adalah konsumsi memori komputer yang lebih kecil dibanding menggunakan bentuk list pada python. 

> It provides fast and efficient operations on arrays of homogeneous data. NumPy extends python into a high-level language for manipulating numerical data, similiar to MATLAB.

Perhatikan contoh operasi perkalian matriks

In [2]:
import numpy as np

# inisialisasi matrik 3x2 dengan nilai random
matNA = np.matrix(np.random.rand(3, 2))
# print matriks pertama
print('Matriks pertama :\n', matNA)

# inisialisasi matrik 2x3 dengan nilai random
matNB = np.matrix(np.random.rand(2, 3))
# print matriks kedua
print('\n Matriks kedua :\n', matNB)

# perkalian matrik menggunakan operator *
matNC = matNA * matNB
# print matriks hasil perkalian
print('\n Matriks hasil perkalian :\n', matNC)

Matriks pertama :
 [[0.93062341 0.50213061]
 [0.12943806 0.93134218]
 [0.45762333 0.68672856]]

 Matriks kedua :
 [[0.80894756 0.33948425 0.28769222]
 [0.89379771 0.34039502 0.04207755]]

 Matriks hasil perkalian :
 [[1.20162872 0.48685475 0.28886154]
 [0.93714011 0.36096642 0.07642692]
 [0.98398969 0.3891149  0.16055053]]


### Membuat matriks


Perhatikan contoh-contoh membuat matriks di bawah ini.


In [11]:
import numpy as np

# Membuata matriks 2x2
matnpA = np.matrix([[1,2],[3,4]])
print('Matriks 2x2 : \n', matnpA)
print(type(matnpA))

Matriks 2x2 : 
 [[1 2]
 [3 4]]
<class 'numpy.matrixlib.defmatrix.matrix'>


In [12]:
# gunakan perintah shape untuk memperoleh informasi ukuran matriks
print('Dimensi matriks :', matnpA.shape)

Dimensi matriks : (2, 2)


Program di bawah ini membentuk matriks dengan panjang elemen 12, dan nilai elemen dimulai dari indeks 0 sampai 11 dengan ukuran 3×4.

In [5]:
from numpy import * 
matrikNP = range(12) 
matrikNP = reshape(matrikNP,(4,3)) 
print(matrikNP)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
